# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rent.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20160301_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rent.models.get_image_path)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='rent.Item')),
            ],
        ),
    ]
